---

- name: Install vim
  apt:
    name: "{{ vim_package }}"
    state: present

- name: Install vim_additional_package
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ vim_additional_packages }}"
